### ISSUE TITLE
mt is missing.

### ISSUE THREAD

**Issue by ghost** [deepnight/ld40-catsAreAssholes#1]
Hello, deepnight. 

I am studying source code of this game, and I wanna run it on my local machine.

When I compile, a problem occurs: 

```
src/Boot.hx:1: characters 8-15 : Type not found : mt.MLib
```

`mt` is not included in `js.hxml`. I am wondering where it comes.

+ If it is a public library, can you send me address?
+ If it is a private library, just ignore this issue. ;)

Sorry for my rude request.

**Comment by deepnight** [comment]
Hi!

Unfortunately, I cannot release mt.* libs as they are internal libs we use at Motion Twin. 
Anyway, mt.MLib is just a simple Math lib (with min,max functions and such), so you may easily replace MLib.* calls with Math.* equivalents ;)

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
Could you give a short explanation what mt.Process does and if it's based on another library?

Kind regards!

**Comment by PlopUser** [comment]
Hi master, 
....
and all mt related stuff like  :  mt.heaps.slib.SpriteLib.TMOD found in Boot.hx File ! 
Sadly, it Seems actually difficult if some try to learn Heap, HaxeLink from sample code.
